### PR TITLE
fix: #1417

### LINKED ISSUE #1417: unsafe usage of freemarker
there is a SSTI vulnerability in halo with unsafe usage of freemarker, the details has be sent by email.

### PR DESCRIPTION
**Pull request by ruibaby**
Close #1417

### CODE REVIEW

**Review by guqing — APPROVED** [review]

File: src/main/java/run/halo/app/config/HaloMvcConfiguration.java [hunk 1]
```diff
@@ -210,23 +207,4 @@ public void addResourceHandlers(ResourceHandlerRegistry registry) {
...
         registry.addConverterFactory(new StringToEnumConverterFactory());
     }
-
-    /**
-     * Configuring view resolver
-     *
-     * @param registry registry
-     */
-    @Override
-    public void configureViewResolvers(ViewResolverRegistry registry) {
```
Comment (JohnNiang) [inline src/main/java/run/halo/app/config/HaloMvcConfiguration.java:220]: Here may be a break change. But I'm not sure now.
