### PR TITLE
fix: Error detection method in the MIMEType and file extension matching stage

### LINKED ISSUE #7661: 存储策略限制类型勾选音频，上传 mp3 文件失败
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: http://192.168.11.25:8090/
- 启动时间: 2025-08-05 17:53
- 版本: 2.21.3
- 构建时间: 2025-07-04 17:23
- Git Commit: bf1083f
- Java: IBM Semeru Runtime Open Edition / 21.0.7+6-LTS
- 数据库: MySQL Community Server - GPL / 8.4.5
- 操作系统: Linux / 6.14.0-24-generic
- 已激活主题: [Nexus 知识库主题 1.5.2](https://www.halo.run/store/apps/app-WDdmT)
- 已启动插件:
  - [增强备份（Backup IMproved） 1.4.0](https://www.halo.run/store/apps/app-dHakX)
  - [内容助手 1.4.1](https://github.com/ruibaby/plugin-content-tools)
  - [Docsme 1.0.2](https://www.halo.run/store/apps/app-yffxw)
  - [MaxKB 小助手 1.4.2](https://www.halo.run/store/apps/app-aWHcE)
  - [社交 IAM 认证 1.5.0](https://www.halo.run/store/apps/app-IXZkJ)
  - [应用市场 1.11.0](https://www.halo.run/store/apps/app-VYJbF)
  - [UPage 1.0.0](https://www.lxware.cn/upage)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.7.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.4.4](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.6.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

创建存储策略限制附件类型勾选音频时，上传 mp3 格式的附件失败，提示
```
文件类型不允许: 文件类型 audio/mpeg 与文件扩展名不匹配，上传被拒绝。
```

### 复现步骤

1. 创建本地存储策略，在限制文件类型中勾选音频
2. 选中新创建的存储策略上传 mp3 文件

### 相关日志输出

```shell

```

### 附加信息

_No response_

### LINKED ISSUE #7903: iPhone中使用Safari在附件页面上传图片的逻辑问题
### Prerequisites

- [x] I have searched for related issues in the [issues](https://github.com/halo-dev/halo/issues) list.
- [x] This is an issue with the Halo project itself. If it is not an issue with the project itself(For example: Installation and deployment issues.), it is recommended to submit it in the [Discussions](https://github.com/halo-dev/halo/discussions).
- [x] I have tried disabling all plugins to rule out plugins as the cause of the problem.
- [x] If it is an issue with plugins and themes, please submit it in the respective plugin and theme repositories.

### System information

- 外部访问地址: ***
- 启动时间: 2025-10-29 18:14
- 版本: 2.21.9
- 构建时间: 2025-09-24 16:32
- Git Commit: fa0b244
- Java: IBM Semeru Runtime Open Edition / 21.0.8+9-LTS
- 数据库: MySQL Community Server - GPL / 8.0.44
- 操作系统: Linux / 6.1.0-39-amd64
- 已激活主题: [Earth 1.13.1](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [Meilisearch 搜索引擎 1.0.2](https://github.com/halo-sigs/plugin-meilisearch)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Data Studio（数据工厂） 1.0.0-alpha.7](https://github.com/halo-sigs/plugin-data-studio)
  - [Shiki 代码高亮 1.0.7](https://github.com/halo-sigs/plugin-shiki)
  - [瞬间 1.13.0](https://github.com/halo-sigs/plugin-moments)
  - [搜索组件 1.7.1](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.11.3](https://www.halo.run/store/apps/app-VYJbF)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)

### What is the project operation method?

Docker

### What happened?

在iPhone中打开safari，进入附件管理页面，选择上传文件，在相册内选择一张实况图后，如果开启了自动转换格式（这个操作是iPhone的原生操作）会将HEIC文件转换成jpeg，此时文件可以上传，待上传后提示，文件类型不允许:文件类型 image/jpeg与文件扩展名不匹配，上传被拒绝。

Image

### Reproduce Steps

_No response_

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by midsmr**
### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Ref: #7903 

#### Which issue(s) this PR fixes:

Fixes #7661
Fixes #7903 

#### Does this PR introduce a user-facing change?

```release-note
修复因文件类型与文件拓展名匹配导致无法上传部分文件的问题
```

### CODE REVIEW

File: api/src/main/java/run/halo/app/infra/utils/FileTypeDetectUtils.java [hunk 1]
```diff
@@ -56,6 +57,12 @@ public static String detectFileExtension(String mimeType) throws MimeTypeExcepti
         return mimeTypes.forName(mimeType).getExtension();
     }
 
+    public static List<String> detectFileExtensions(String mimeType) throws MimeTypeException {
+        //这里新增一个方法，不直接修改detectFileExtension，以防有其他软件使用了该API
```
Comment (JohnNiang) [inline api/src/main/java/run/halo/app/infra/utils/FileTypeDetectUtils.java]:
```suggestion
```

File: application/src/test/java/run/halo/app/infra/utils/FileTypeDetectUtilsTest.java
Comment (JohnNiang) [inline application/src/test/java/run/halo/app/infra/utils/FileTypeDetectUtilsTest.java:137]: 建议也为这个测试添加更多的用例。

**Comment by midsmr** [comment]
@JohnNiang 您好，已经按照您的建议进行了更改，同时优化了检测方法，不使用for循环了

**Review by JohnNiang — APPROVED** [review]
Thank you for your first contribution!

/lgtm
