### PR TITLE
fix: the search for comments by username yields empty results

### LINKED ISSUE #4465: Console 端评论根据用户搜索为空
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

_No response_

### 问题描述

当前 console 根据用户搜索时，返回的结果始终为空，如下所示：

image

### 期望结果

根据用户搜索时，能够正确返回对应用户的评论

/area console
/kind bug 

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?

/kind bug
/area console
/milestone 2.9.x

#### What this PR does / why we need it:

Console 评论列表中，使用用户名查询时携带 kind

#### How to test it?

在 Console 端评论列表，选中右上角评论者，进行选择。

#### Which issue(s) this PR fixes:

Fixes #4465 

#### Does this PR introduce a user-facing change?
```release-note
解决评论列表根据评论者条件筛选时为空的问题
```

### CODE REVIEW

File: console/src/modules/contents/comments/CommentList.vue [hunk 1]
```diff
@@ -95,6 +102,7 @@ const {
       sort: [selectedSort.value].filter(Boolean) as string[],
       keyword: keyword.value,
       ownerName: selectedUser.value,
+      ownerKind: selectedUserKind.value,
```
Comment (ruibaby) [inline console/src/modules/contents/comments/CommentList.vue:105]:
```suggestion
			// toDO
      ownerKind: selectedUser.value ? 'User' : undefined,
```

**Review by ruibaby — CHANGES_REQUESTED** [review]

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by ruibaby — APPROVED** [review]
