### PR TITLE
fix: category and tag query parameters in post query

### LINKED ISSUE #2439: 后台（Console）文章筛选功能部分参数无效
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

2.0.0-prerelease

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

_No response_

### 发生了什么？

后台文章筛选接口的 `categories` `tags` `contributors` 参数无效。看了一下后端的代码，是否是因为这里取值不正确？

https://github.com/halo-dev/halo/blob/fe031f32825321085d7744bfd32ecd024cc6c10f/src/main/java/run/halo/app/content/PostQuery.java#L24-L37

/kind bug
/milestone 2.0
/area core

/cc @guqing

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind api-change
/kind improvement
/area core
/milestone 2.0
#### What this PR does / why we need it:
修复文章列表的分类、标签查询参数方法名和取值不一致导致无效问题
#### Which issue(s) this PR fixes:

Fixes #2439

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: src/main/java/run/halo/app/content/PostQuery.java [hunk 1]
```diff
@@ -20,17 +20,17 @@ public PostQuery(MultiValueMap<String, String> queryParams) {
     }
 
     @Nullable
-    public Set<String> getContributors() {
+    public Set<String> getContributor() {
```
Comment (JohnNiang) [inline src/main/java/run/halo/app/content/PostQuery.java:23]: 这样会不会更好，能够保留 getContributor`s` 。
```diff
+   @Schema(name = "contributors")
    public Set<String> getContributors() {
        return listToSet(queryParams.get("contributor"));
    }
```

Comment (guqing) [reply src/main/java/run/halo/app/content/PostQuery.java:23]: > 这样会不会更好，能够保留 getContributor`s` 。
> 
> ```diff
> +   @Schema(name = "contributor")
>     public Set<String> getContributors() {
>         return listToSet(queryParams.get("contributor"));
>     }
> ```

nice suggestion

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by ruibaby — COMMENTED** [review]
/lgtm
