### PR TITLE
fix(security): prevent XSS vulnerability in snapshot diff component

### LINKED ISSUE #8315: Security: XSS Vulnerability in Snapshot Diff Component
### Prerequisites

- [x] I have searched for related issues in the [issues](https://github.com/halo-dev/halo/issues) list.
- [x] This is an issue with the Halo project itself. If it is not an issue with the project itself(For example: Installation and deployment issues.), it is recommended to submit it in the [Discussions](https://github.com/halo-dev/halo/discussions).
- [x] I have tried disabling all plugins to rule out plugins as the cause of the problem.
- [x] If it is an issue with plugins and themes, please submit it in the respective plugin and theme repositories.

### System information

- bug

### What is the project operation method?

Source Code

### Description
The snapshot diff component (`SnapshotDiffContent.vue`) directly renders user-controlled content using `innerHTML` and `v-html` without sanitization, creating a cross-site scripting (XSS) vulnerability.

### Affected Files
- `ui/console-src/components/snapshots/SnapshotDiffContent.vue`

### Vulnerability Details

**Location:** Lines 59-61, 242, 258, and 291

The component directly sets `innerHTML` and uses `v-html` with unsanitized content:

// Lines 59-61
const oldContent = document.createElement("div");
oldContent.innerHTML = snapshot.value.old.content || "";
const newContent = document.createElement("div");
newContent.innerHTML = snapshot.value.new.content || "";

// Lines 242, 258
<div class="snapshot-content markdown-body" v-html="snapshot?.old.content"></div>
<div class="snapshot-content markdown-body" v-html="snapshot?.new.content"></div>

// Line 291
<div class="snapshot-content markdown-body" v-html="diffContent"></div>

### Reproduce Steps

_No response_

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glowsenior**
What type of PR is this?
/kind cleanup
/area core

What this PR does / why we need it:
This PR fixes a critical XSS (Cross-Site Scripting) vulnerability in the snapshot diff component where user-controlled content was rendered without sanitization.

Which issue(s) this PR fixes:
Fixes #8315

Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

File: ui/console-src/components/snapshots/SnapshotDiffContent.vue [hunk 1]
```diff
@@ -8,6 +8,7 @@ import {
 } from "@halo-dev/components";
 import { useQuery } from "@tanstack/vue-query";
 import { useLocalStorage } from "@vueuse/core";
+import DOMPurify from "dompurify";
```
Comment (ruibaby) [inline ui/console-src/components/snapshots/SnapshotDiffContent.vue:11]: Use sanitize-html instead, since it’s already a dependency in the project.

Comment (glowsenior) [reply ui/console-src/components/snapshots/SnapshotDiffContent.vue:11]: Does this mean I shouldn't use dompurify? 

Got it. I will update asap!

Comment (ruibaby) [reply ui/console-src/components/snapshots/SnapshotDiffContent.vue:11]: Yes, sanitize-html and DomPurify should belong to the same category of libraries. If functionality allows, we shouldn’t install both at the same time.

Comment (glowsenior) [reply ui/console-src/components/snapshots/SnapshotDiffContent.vue:11]: I have committed just now. Please check that.

**Comment by ruibaby** [comment]
Sorry for the late response. After testing, I found that the current approach may cause some rich text content to not display properly. Given that our editor supports a wide variety of formats, we need thorough testing to ensure all content renders correctly. I’ll review this as soon as possible.

**Comment by glowsenior** [comment]
> Sorry for the late response. After testing, I found that the current approach may cause some rich text content to not display properly. Given that our editor supports a wide variety of formats, we need thorough testing to ensure all content renders correctly. I’ll review this as soon as possible.

ok, thanks for your reply, I will wait for a good result.

**Comment by ruibaby** [comment]
@glowsenior 

Sorry for the late response. Based on my latest investigation, it turns out using dompurify is indeed the better approach (you were right all along). dompurify has a more lenient default behavior and only filters out dangerous content, while sanitize-html uses a whitelist approach, which means we’d need to manually adjust tons of configurations. I’ve reverted the last commit and it’s ready to merge now.
