### PR TITLE
fix: signup form overlaps with locale form.

### LINKED ISSUE #3695: chrome浏览器访问注册界面，元素重叠问题
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://demo.halo.run/

### 发生了什么？

chrome浏览器直接访问https://demo.halo.run/ 站点的注册界面，“已有账号 立即登录”与“简体中文”文字重叠。如下图所示：
image

Chrome浏览器显示比例：100%。
windows显示器设置如下图：
image

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by hughding**
#### What type of PR is this?
/kind improvement
/area console

#### What this PR does / why we need it:
此修改对登录、注册界面原有风格无影响。解决了1920*1080分辨率下，注册界面，“已有账号 立即登录”与“简体中文”文字重叠问题

#### Which issue(s) this PR fixes:
Fixes #3695

#### Does this PR introduce a user-facing change?
```release-note
解决1920*1080分辨率下，注册界面，“已有账号 立即登录”与“简体中文”文字重叠问题
```

### CODE REVIEW

File: console/src/modules/system/users/Binding.vue [hunk 1]
```diff
@@ -51,7 +51,7 @@ function handleChangeType() {
 const isLoginType = computed(() => type.value !== "signup");
 </script>
 <template>
-  <div class="flex h-screen flex-col items-center bg-white/90 pt-[30vh]">
+  <div class="flex h-screen flex-col items-center bg-white/90 pt-[20vh]">
```
Comment (ruibaby) [inline console/src/modules/system/users/Binding.vue:54]:
```suggestion
  <div
    class="flex h-screen flex-col items-center bg-white/90 pt-[20vh] sm:pt-[30vh]"
  >
```

推荐通过这样的方式来适配分辨率，而不是直接修改这个值。

File: console/src/modules/system/users/Login.vue [hunk 2]
```diff
@@ -68,7 +68,7 @@ watch(
 );
 </script>
 <template>
-  <div class="flex h-screen flex-col items-center bg-white/90 pt-[30vh]">
+  <div class="flex h-screen flex-col items-center bg-white/90 pt-[20vh]">
```
Comment (ruibaby) [inline console/src/modules/system/users/Login.vue:71]:
```suggestion
  <div
    class="flex h-screen flex-col items-center bg-white/90 pt-[20vh] sm:pt-[30vh]"
  >
```

**Review by ruibaby — CHANGES_REQUESTED** [review]

**Review by ruibaby — APPROVED** [review]
/lgtm
