### PR TITLE
fix: add keyword search functionality to AuthProvider list

### LINKED ISSUE #3948: 身份认证筛选无效
### 是什么版本出现了此问题？

2.5.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

_No response_

### 发生了什么？

身份认证使用关键字搜索无效，
image

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by JustinLiang522**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

添加关键字搜索功能到认证方式列表

#### Which issue(s) this PR fixes:

Fixes #3948

#### Does this PR introduce a user-facing change?

```release-note
修复 Console 端认证方式列表无法使用搜索的问题。
```

### CODE REVIEW

File: console/src/modules/system/auth-providers/AuthProviders.vue [hunk 1]
```diff
@@ -20,6 +22,29 @@ const {
     const { data } = await apiClient.authProvider.listAuthProviders();
     return data;
   },
+  initialData: [],
+});
+
+const keyword = ref("");
+let fuse: Fuse<ListedAuthProvider> | undefined = undefined;
+
+watch(
```
Comment (ruibaby) [inline console/src/modules/system/auth-providers/AuthProviders.vue:31]: 推荐在 useQuery 那里使用 onSuccess 的回调函数来创建 fuse 的索引。

```diff
const {
  data: authProviders,
  isLoading,
  refetch,
} = useQuery<ListedAuthProvider[]>({
  queryKey: ["auth-providers"],
  queryFn: async () => {
    const { data } = await apiClient.authProvider.listAuthProviders();
    return data;
  },
+  onSuccess (data) {
+    // create fuse index
+    fuse = new Fuse()
+  }
  initialData: [],
});
```

**Review by ruibaby — CHANGES_REQUESTED** [review]

**Review by ruibaby — COMMENTED** [review]
image

/lgtm

**Review by guqing — APPROVED** [review]
/approve

**Review by ruibaby — APPROVED** [review]
