### PR TITLE
fix: post list sorting parameter not working

### LINKED ISSUE #6534: 2.19.0-rc.2版本   postFinder.list 方法排序无效
### 系统信息

- 外部访问地址: http://localhost:8088/
- 启动时间: 2024-08-28 11:08
- 版本: 2.19.0-rc.2
- 构建时间: 2024-08-27 20:48
- Git Commit: 2815678
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.10.16.3-microsoft-standard-WSL2
- 已激活主题: Oyiso 1.1.1
- 已启动插件:
  - [highlight.js 代码高亮 1.2.1](https://github.com/halo-sigs/plugin-highlightjs)
  - [豆瓣 1.1.6](https://github.com/chengzhongxue/plugin-douban)
  - [朋友圈 1.3.2](https://github.com/chengzhongxue/plugin-friends)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [文章限制阅读 Pro 1.2.3](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.3.3](https://github.com/halo-sigs/plugin-links)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [搜索组件 1.6.1](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 发生了什么？

postFinder.list({page: 1, size: 8, sort: {'stats.visit,desc'}}) 当前语法是否错误

### 复现步骤

_No response_

### 相关日志输出

_No response_

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by guqing**
#### What type of PR is this?
/kind bug
/area core
/milestone 2.19.x

#### What this PR does / why we need it:
修复 postFinder 的 list 排序参数不生效的问题

此问题由于 https://github.com/halo-dev/halo/pull/6531 导致

#### Which issue(s) this PR fixes:
Fixes #6534

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

File: application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java [hunk 1]
```diff
@@ -338,8 +339,8 @@ public ListOptions toListOptions() {
 
         public PageRequest toPageRequest() {
             var resolvedSort = Optional.of(SortUtils.resolve(sort))
-                .filter(Sort::isUnsorted)
-                .orElse(defaultSort());
+                .filter(Predicate.not(Sort::isUnsorted))
+                .orElseGet(PostFinderImpl::defaultSort);
```
Comment (JohnNiang) [inline application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java:343]: 这里建议将默认排序直接 append 到 sort 后。

Comment (guqing) [reply application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java]: Done

**Review by JohnNiang — APPROVED** [review]
It works very well.

**Review by ruibaby — APPROVED** [review]
/lgtm
